version: "3"
services:
  nginx:
    build: services/nginx
    ports:
      - "${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}"
      - "${NGINX_MQTT_PORT}:${NGINX_MQTT_PORT}"
    depends_on:
      - back
    restart: unless-stopped
  back:
    build:
      context: .
      dockerfile: packages/back/Dockerfile
    env_file: .env
    expose:
      - "${BACK_PORT}"
    restart: unless-stopped
  front:
    build:
      context: .
      dockerfile: packages/front/Dockerfile
      args:
        FRONT_PORT: "${FRONT_PORT}"
    expose:
      - "${FRONT_PORT}"
    depends_on:
      - back
    restart: unless-stopped
  biot:
    build:
      context: .
      dockerfile: packages/biot/Dockerfile
    env_file: .env
    expose:
      - "${BIOT_PORT}"
    depends_on:
      - back
    restart: unless-stopped
  worker:
    build:
      context: .
      dockerfile: packages/worker/Dockerfile
    env_file: .env
    expose:
      - "${WORKER_PORT}"
    restart: unless-stopped
  thing:
    build:
      context: .
      dockerfile: packages/thing/Dockerfile
    env_file: .env
    expose:
      - "${THING_SOCKET_PORT}"
    restart: unless-stopped
