version: '2'
services:
  nginx:
    build: nginx
    ports:
      - "${NGINX_EXTERNAL_PORT}:${NGINX_INTERNAL_PORT}"
    links:
      - node1
      - node2
    restart: always
  node1:
    env_file:
      - iot-server/.env
    expose:
      - "${NODE_PORT}"
    links:
      - mongo
      - redis
  node2:
    env_file:
      - iot-server/.env
    expose:
      - "${NODE_PORT}"
    links:
      - mongo
      - redis
  mongo:
    image: mongo
    expose:
      - "${MONGO_PORT}"
    restart: always
  redis:
    image: redis
    expose:
      - "${REDIS_PORT}"
    restart: always
  biot:
    env_file:
      - biot/.env
    expose:
      - "${BIOT_PORT}"
    links:
      - nginx