version: '3'
services:
  redis:
    image: redis
    expose:
      - "${REDIS_PORT}"
    restart: unless-stopped
  mosquitto:
    build: 
      context: services/mosquitto
      args:
        MQTT_BROKER_USERNAME: "${MQTT_BROKER_USERNAME}"
        MQTT_BROKER_PASSWORD: "${MQTT_BROKER_PASSWORD}"
    expose:
      - "${MQTT_BROKER_PORT}"
    restart: unless-stopped