version: '3'
services:
  nginx:
    build: nginx
    ports:
      - "${NGINX_HTTP_EXTERNAL_PORT}:${NGINX_HTTP_INTERNAL_PORT}"
      - "${NGINX_MQTT_EXTERNAL_PORT}:${NGINX_MQTT_INTERNAL_PORT}"
    links:
      - server1
      - server2
  server1:
    env_file: iot-server/.env
    expose:
      - "${SERVER_PORT}"
  server2:
    env_file: iot-server/.env
    expose:
      - "${SERVER_PORT}"
  redis:
    image: redis
    expose:
      - "${REDIS_PORT}"
  mosquitto:
    build: mosquitto
    expose:
      - "${MOSQUITTO_PORT}"
  biot:
    env_file: biot/.env
    expose:
      - "${BIOT_PORT}"
    links:
      - nginx
  worker:
    env_file: iot-worker/.env
    expose:
      - "${WORKER_PORT}"
    links:
      - biot
  web1:
    build: iot-web
    expose:
      - "${WEB_PORT}"
    links:
      - nginx
  web2:
    build: iot-web
    expose:
      - "${WEB_PORT}"
    links:
      - nginx 
