version: '2'
services:
  nginx:
    build: nginx
    ports:
      - "${NGINX_HTTP_EXTERNAL_PORT}:${NGINX_HTTP_INTERNAL_PORT}"
      - "${NGINX_MQTT_EXTERNAL_PORT}:${NGINX_MQTT_INTERNAL_PORT}"
    links:
      - node1
      - node2
  node1:
    env_file:
      - iot-server/.env
    expose:
      - "${NODE_PORT}"
    links:
      - mongo
      - redis
      - mosquitto1
      - mosquitto2
  node2:
    env_file:
      - iot-server/.env
    expose:
      - "${NODE_PORT}"
    links:
      - mongo
      - redis
      - mosquitto1
      - mosquitto2
  mongo:
    image: mongo
    expose:
      - "${MONGO_PORT}"
  redis:
    image: redis
    expose:
      - "${REDIS_PORT}"
  mosquitto1:
    build: mosquitto
    expose:
      - "${MOSQUITTO_PORT}"
  mosquitto2:
    build: mosquitto
    expose:
      - "${MOSQUITTO_PORT}"
  biot:
    env_file:
      - biot/.env
    expose:
      - "${BIOT_PORT}"
    links:
      - nginx